### ISSUE TITLE
happen 'underfined' when PolsArray.saveToFile

### ISSUE THREAD

**Issue by cyl19970726** [0xPolygonHermez/pilcom#36]
# Issue 
The program happens the below error when running https://github.com/cyl19970726/eigen-zkvm/tree/single_poseidon_recursive/starkjs#4-r1cs----pil
![截屏2023-06-14 19 58 01](https://github.com/0xPolygonHermez/pilcom/assets/52317293/c080a6c7-2b59-4713-bd02-cdb68c8d0d95)

## Issue Code Position 
https://github.com/0xPolygonHermez/pilcom/blob/main/src/polsarray.js#L129

# Fix 
Initialize to 0 when 'undefined' appears.
![截屏2023-06-14 20 03 51](https://github.com/0xPolygonHermez/pilcom/assets/52317293/85eb7aba-ec85-4498-b3a3-7d0eeee73c72)

**Comment by eigmax** [comment]
Should declare at least one public input or output.

**Comment by zkronos73** [comment]
It's very important to set the values explicitly, otherwise errors may be introduced.
